### ISSUE TITLE
Problém s zobrazovaním rozsireni pro chatgpt

### ISSUE THREAD

**Issue by danecek12345** [MJakubec/UserScripts#1]
Přestal mi fungovat skript pro tampermonkey který umožnoval z chatgpt udělat zkoušejícího, přestala se zobrazovat nabídka s otázkama, která má být nad chatem.

**Comment by MJakubec** [comment]
This issue has been caused by recent changes in the ChatGPT site URL structure. Now it is fixed in the master branch.
